#!/usr/bin/env python3
"""Repository-local Cruthúnas CR-0 governance CLI.

This tool validates evidence governance. It does not verify mathematical truth.
"""

from __future__ import annotations

import argparse
import json
import re
import subprocess
import sys
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[1]
PROJECT_PATH = ROOT / "cruthunas" / "project.json"
GENERATED_HEADER = (
    "<!-- GENERATED by `python scripts/cruthunas.py adapters sync`; "
    "edit cruthunas/skills/cruthunas-govern/SKILL.md instead. -->\n\n"
)

EPISTEMIC_CLASSES = {"MATHEMATICAL", "COMPUTATIONAL", "HYBRID", "INFRASTRUCTURE"}
VERIFICATION_STATES = {
    "UNCHECKED",
    "INTERNALLY_VERIFIED",
    "INDEPENDENTLY_REPRODUCED",
    "CERTIFICATE_CHECKED",
    "FORMALLY_VERIFIED",
    "EXTERNALLY_REVIEWED",
}
LIFECYCLE_STATES = {"OPEN", "WORKING", "SUPERSEDED", "RETRACTED"}
EVIDENCE_TYPES = {
    "REPRODUCTION",
    "PROOF_PACKAGE",
    "REDUCTION",
    "UNSAT_CERTIFICATE",
    "SEARCH_INFRASTRUCTURE",
    "SYMMETRY_REDUCTION",
    "SAT_WITNESS",
    "FORMAL_PROOF",
    "EXTERNAL_REVIEW",
}
SHA256_RE = re.compile(r"^[0-9a-f]{64}$")


class GovernanceError(Exception):
    pass


def load_json(path: Path) -> dict[str, Any]:
    try:
        value = json.loads(path.read_text(encoding="utf-8"))
    except FileNotFoundError as exc:
        raise GovernanceError(f"missing file: {path.relative_to(ROOT)}") from exc
    except json.JSONDecodeError as exc:
        raise GovernanceError(f"invalid JSON in {path.relative_to(ROOT)}: {exc}") from exc
    if not isinstance(value, dict):
        raise GovernanceError(f"top-level JSON must be an object: {path.relative_to(ROOT)}")
    return value


def project_files() -> tuple[dict[str, Any], dict[str, dict[str, Any]]]:
    project = load_json(PROJECT_PATH)
    named = {
        "claims": load_json(ROOT / project["claim_registry"]),
        "ledger": load_json(ROOT / project["ledger"]),
        "evidence": load_json(ROOT / project["evidence_registry"]),
        "transitions": load_json(ROOT / project["transition_registry"]),
        "sources": load_json(ROOT / project["source_registry"]),
    }
    return project, named


def add(errors: list[str], message: str) -> None:
    errors.append(message)


def require_string(value: Any, context: str, errors: list[str]) -> bool:
    if not isinstance(value, str) or not value.strip():
        add(errors, f"{context} must be a non-empty string")
        return False
    return True


def unique_objects(values: Any, collection_name: str, key: str, errors: list[str]) -> dict[str, dict[str, Any]]:
    result: dict[str, dict[str, Any]] = {}
    if not isinstance(values, list):
        add(errors, f"{collection_name} must be an array")
        return result
    for index, value in enumerate(values):
        if not isinstance(value, dict):
            add(errors, f"{collection_name}[{index}] must be an object")
            continue
        identifier = value.get(key)
        if not require_string(identifier, f"{collection_name}[{index}].{key}", errors):
            continue
        assert isinstance(identifier, str)
        if identifier in result:
            add(errors, f"duplicate {collection_name} {key}: {identifier}")
        else:
            result[identifier] = value
    return result


def validate_claim_dependencies(claims: dict[str, dict[str, Any]], errors: list[str]) -> None:
    graph: dict[str, list[str]] = {}
    for claim_id, claim in claims.items():
        dependencies = claim.get("depends_on", [])
        if not isinstance(dependencies, list) or not all(isinstance(item, str) and item for item in dependencies):
            add(errors, f"{claim_id}: depends_on must be an array of claim IDs")
            dependencies = []
        graph[claim_id] = dependencies
        for dependency in dependencies:
            if dependency not in claims:
                add(errors, f"{claim_id}: unknown dependency {dependency}")

    visiting: set[str] = set()
    visited: set[str] = set()

    def visit(claim_id: str, path: list[str]) -> None:
        if claim_id in visited:
            return
        if claim_id in visiting:
            add(errors, "claim dependency cycle: " + " -> ".join(path + [claim_id]))
            return
        visiting.add(claim_id)
        for dependency in graph.get(claim_id, []):
            if dependency in claims:
                visit(dependency, path + [claim_id])
        visiting.remove(claim_id)
        visited.add(claim_id)

    for claim_id in claims:
        visit(claim_id, [])


def expected_adapter_content(project: dict[str, Any]) -> str:
    source = ROOT / project["canonical_skill"]
    content = source.read_text(encoding="utf-8").rstrip() + "\n"
    return GENERATED_HEADER + content


def adapter_errors(project: dict[str, Any]) -> list[str]:
    errors: list[str] = []
    source = ROOT / project.get("canonical_skill", "")
    if not source.is_file():
        return [f"missing canonical skill: {source.relative_to(ROOT)}"]
    expected = expected_adapter_content(project)
    adapters = project.get("adapters")
    if not isinstance(adapters, list) or not adapters:
        return ["project adapters must be a non-empty array"]
    for adapter in adapters:
        if not isinstance(adapter, str) or not adapter:
            add(errors, "adapter path must be a non-empty string")
            continue
        path = ROOT / adapter
        if not path.is_file():
            add(errors, f"missing generated adapter: {adapter}")
        elif path.read_text(encoding="utf-8") != expected:
            add(errors, f"adapter drift: {adapter}; run `python scripts/cruthunas.py adapters sync`")
    return errors


def sync_adapters(project: dict[str, Any]) -> None:
    expected = expected_adapter_content(project)
    for adapter in project["adapters"]:
        path = ROOT / adapter
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(expected, encoding="utf-8", newline="\n")
        print(f"synced {adapter}")


def validate_all() -> list[str]:
    errors: list[str] = []
    try:
        project, named = project_files()
    except (GovernanceError, KeyError) as exc:
        return [str(exc)]

    if project.get("framework") != "Cruthúnas":
        add(errors, "project framework must be exactly 'Cruthúnas'")
    if project.get("framework_state") != "CR-0":
        add(errors, "this bootstrap must remain CR-0 until separately promoted")
    if project.get("governance_skill") != "cruthunas-govern":
        add(errors, "canonical governance skill must be cruthunas-govern")

    for schema in (
        ROOT / "cruthunas/schemas/evidence.schema.json",
        ROOT / "cruthunas/schemas/transition.schema.json",
    ):
        if not schema.is_file():
            add(errors, f"missing typed schema: {schema.relative_to(ROOT)}")

    claims = unique_objects(named["claims"].get("claims"), "claims", "id", errors)
    ledger = unique_objects(named["ledger"].get("entries"), "ledger entries", "claim_id", errors)
    evidence = unique_objects(named["evidence"].get("evidence"), "evidence", "id", errors)
    sources = unique_objects(named["sources"].get("sources"), "sources", "id", errors)

    if set(ledger) != set(claims):
        missing = sorted(set(claims) - set(ledger))
        extra = sorted(set(ledger) - set(claims))
        if missing:
            add(errors, "claims missing from Cruthúnas ledger: " + ", ".join(missing))
        if extra:
            add(errors, "ledger entries without registered claims: " + ", ".join(extra))

    validate_claim_dependencies(claims, errors)

    for source_id, source in sources.items():
        if source.get("kind") != "repository-document":
            add(errors, f"{source_id}: unsupported source kind {source.get('kind')!r}")
        path_value = source.get("path")
        if require_string(path_value, f"{source_id}.path", errors):
            assert isinstance(path_value, str)
            if not (ROOT / path_value).is_file():
                add(errors, f"{source_id}: source path does not exist: {path_value}")
        require_string(source.get("revision_pin"), f"{source_id}.revision_pin", errors)
        allowed = source.get("allowed_claim_ids")
        if not isinstance(allowed, list) or not allowed:
            add(errors, f"{source_id}: allowed_claim_ids must be non-empty")
        else:
            for claim_id in allowed:
                if claim_id not in claims:
                    add(errors, f"{source_id}: unknown allowed claim {claim_id}")

    for evidence_id, record in evidence.items():
        claim_id = record.get("claim_id")
        if claim_id not in claims:
            add(errors, f"{evidence_id}: unknown claim {claim_id!r}")
        if record.get("type") not in EVIDENCE_TYPES:
            add(errors, f"{evidence_id}: unsupported evidence type {record.get('type')!r}")
        if record.get("epistemic_class") not in EPISTEMIC_CLASSES:
            add(errors, f"{evidence_id}: unsupported epistemic class")
        if record.get("verification_state") not in VERIFICATION_STATES:
            add(errors, f"{evidence_id}: unsupported verification state")
        paths = record.get("paths")
        if not isinstance(paths, list) or not paths:
            add(errors, f"{evidence_id}: paths must be non-empty")
        else:
            for path_value in paths:
                if not isinstance(path_value, str) or not path_value:
                    add(errors, f"{evidence_id}: invalid artifact path")
                elif not (ROOT / path_value).is_file():
                    add(errors, f"{evidence_id}: artifact path does not exist: {path_value}")
        commands = record.get("commands")
        if not isinstance(commands, list) or not commands or not all(isinstance(command, str) and command.strip() for command in commands):
            add(errors, f"{evidence_id}: commands must be non-empty strings")
        if not isinstance(record.get("environment"), dict) or not record["environment"]:
            add(errors, f"{evidence_id}: environment must be a non-empty object")
        require_string(record.get("source_revision"), f"{evidence_id}.source_revision", errors)
        if not isinstance(record.get("clean_room_verifier"), bool):
            add(errors, f"{evidence_id}: clean_room_verifier must be boolean")
        require_string(record.get("limitations"), f"{evidence_id}.limitations", errors)
        hashes = record.get("artifact_hashes", [])
        if not isinstance(hashes, list):
            add(errors, f"{evidence_id}: artifact_hashes must be an array")
        else:
            for index, item in enumerate(hashes):
                if not isinstance(item, dict):
                    add(errors, f"{evidence_id}.artifact_hashes[{index}] must be an object")
                    continue
                require_string(item.get("artifact"), f"{evidence_id}.artifact_hashes[{index}].artifact", errors)
                digest = item.get("sha256")
                if not isinstance(digest, str) or not SHA256_RE.fullmatch(digest):
                    add(errors, f"{evidence_id}.artifact_hashes[{index}].sha256 is invalid")

    chains_raw = named["transitions"].get("chains")
    if not isinstance(chains_raw, list):
        add(errors, "transition chains must be an array")
        chains_raw = []
    chains: dict[str, dict[str, Any]] = {}
    transition_ids: set[str] = set()
    for index, chain in enumerate(chains_raw):
        if not isinstance(chain, dict):
            add(errors, f"transition chains[{index}] must be an object")
            continue
        claim_id = chain.get("claim_id")
        if not isinstance(claim_id, str) or not claim_id:
            add(errors, f"transition chains[{index}].claim_id is invalid")
            continue
        if claim_id in chains:
            add(errors, f"duplicate transition chain for {claim_id}")
        chains[claim_id] = chain

    if set(chains) != set(claims):
        missing = sorted(set(claims) - set(chains))
        extra = sorted(set(chains) - set(claims))
        if missing:
            add(errors, "claims missing transition chains: " + ", ".join(missing))
        if extra:
            add(errors, "transition chains for unknown claims: " + ", ".join(extra))

    for claim_id, entry in ledger.items():
        gate = entry.get("gate")
        if not isinstance(gate, int) or not 1 <= gate <= 6:
            add(errors, f"{claim_id}: gate must be an integer from 1 to 6")
            continue
        epistemic = entry.get("epistemic_class")
        verification = entry.get("verification_state")
        lifecycle = entry.get("lifecycle_state")
        if epistemic not in EPISTEMIC_CLASSES:
            add(errors, f"{claim_id}: unsupported epistemic class {epistemic!r}")
        if verification not in VERIFICATION_STATES:
            add(errors, f"{claim_id}: unsupported verification state {verification!r}")
        if lifecycle not in LIFECYCLE_STATES:
            add(errors, f"{claim_id}: unsupported lifecycle state {lifecycle!r}")

        source_ids = entry.get("source_ids")
        if not isinstance(source_ids, list) or not source_ids:
            add(errors, f"{claim_id}: source_ids must be non-empty")
        else:
            for source_id in source_ids:
                source = sources.get(source_id)
                if source is None:
                    add(errors, f"{claim_id}: unknown source {source_id}")
                elif claim_id not in source.get("allowed_claim_ids", []):
                    add(errors, f"{claim_id}: source boundary violation for {source_id}")

        evidence_ids = entry.get("evidence_ids")
        if not isinstance(evidence_ids, list):
            add(errors, f"{claim_id}: evidence_ids must be an array")
            evidence_ids = []
        for evidence_id in evidence_ids:
            record = evidence.get(evidence_id)
            if record is None:
                add(errors, f"{claim_id}: unknown evidence {evidence_id}")
                continue
            if record.get("claim_id") != claim_id:
                add(errors, f"{claim_id}: evidence {evidence_id} belongs to another claim")
            if record.get("epistemic_class") != epistemic:
                add(errors, f"{claim_id}: epistemic mismatch with evidence {evidence_id}")
            if record.get("verification_state") != verification:
                add(errors, f"{claim_id}: verification mismatch with evidence {evidence_id}")

        chain = chains.get(claim_id)
        if chain is None:
            continue
        records = chain.get("records")
        if not isinstance(records, list) or not records:
            add(errors, f"{claim_id}: transition records must be non-empty")
            continue
        expected_from = 0
        gate_3_to_4_found = False
        last_id = None
        for index, record in enumerate(records):
            if not isinstance(record, dict):
                add(errors, f"{claim_id}: transition[{index}] must be an object")
                continue
            transition_id = record.get("id")
            if not isinstance(transition_id, str) or not transition_id:
                add(errors, f"{claim_id}: transition[{index}].id is invalid")
            elif transition_id in transition_ids:
                add(errors, f"duplicate transition id: {transition_id}")
            else:
                transition_ids.add(transition_id)
                last_id = transition_id
            from_gate = record.get("from_gate")
            to_gate = record.get("to_gate")
            if from_gate != expected_from or to_gate != expected_from + 1:
                add(errors, f"{claim_id}: non-contiguous transition at record {index}")
            if isinstance(to_gate, int):
                expected_from = to_gate
            require_string(record.get("date"), f"{claim_id}.{transition_id}.date", errors)
            require_string(record.get("actor"), f"{claim_id}.{transition_id}.actor", errors)
            require_string(record.get("reason"), f"{claim_id}.{transition_id}.reason", errors)
            require_string(record.get("source_revision"), f"{claim_id}.{transition_id}.source_revision", errors)
            if not isinstance(record.get("bootstrap_import"), bool):
                add(errors, f"{claim_id}.{transition_id}: bootstrap_import must be boolean")
            transition_evidence = record.get("evidence_ids")
            if not isinstance(transition_evidence, list):
                add(errors, f"{claim_id}.{transition_id}: evidence_ids must be an array")
                transition_evidence = []
            for evidence_id in transition_evidence:
                evidence_record = evidence.get(evidence_id)
                if evidence_record is None:
                    add(errors, f"{claim_id}.{transition_id}: unknown evidence {evidence_id}")
                elif evidence_record.get("claim_id") != claim_id:
                    add(errors, f"{claim_id}.{transition_id}: cross-claim evidence {evidence_id}")
            if from_gate == 2 and to_gate == 3 and not transition_evidence:
                add(errors, f"{claim_id}: Gate 2 to Gate 3 requires evidence")
            if from_gate == 3 and to_gate == 4:
                gate_3_to_4_found = True
                if not transition_evidence:
                    add(errors, f"{claim_id}: Gate 3 to Gate 4 requires registered evidence")
        if expected_from != gate:
            add(errors, f"{claim_id}: transition chain ends at Gate {expected_from}, ledger says Gate {gate}")
        if entry.get("current_transition_id") != last_id:
            add(errors, f"{claim_id}: current_transition_id does not match chain tail")
        if gate >= 4 and not gate_3_to_4_found:
            add(errors, f"{claim_id}: missing required Gate 3 to Gate 4 registration")
        if gate >= 3 and not evidence_ids:
            add(errors, f"{claim_id}: Gate {gate} requires linked evidence")

        claim = claims.get(claim_id, {})
        status = claim.get("status")
        if status == "open":
            if gate > 2 or verification != "UNCHECKED" or lifecycle != "OPEN":
                add(errors, f"{claim_id}: open target must remain Gate <=2, UNCHECKED, OPEN")
        elif status == "candidate-proof":
            if gate != 4 or verification not in {"INTERNALLY_VERIFIED", "INDEPENDENTLY_REPRODUCED"}:
                add(errors, f"{claim_id}: candidate proof must remain Gate 4 with internal verification")
        elif status == "reproduction-verified":
            if gate != 4 or verification != "INDEPENDENTLY_REPRODUCED":
                add(errors, f"{claim_id}: reproduction requires Gate 4 independently reproduced evidence")
        elif status == "certified-obstruction":
            if gate != 4 or verification != "CERTIFICATE_CHECKED":
                add(errors, f"{claim_id}: certified obstruction requires Gate 4 certificate checking")
        elif status == "attack-surface":
            if gate > 4 or verification in {"FORMALLY_VERIFIED", "EXTERNALLY_REVIEWED"}:
                add(errors, f"{claim_id}: attack surface cannot exceed internal Gate 4")

    errors.extend(adapter_errors(project))
    return errors


def show_status() -> int:
    project, named = project_files()
    claims = {item["id"]: item for item in named["claims"]["claims"]}
    print(f"Cruthúnas {project['framework_state']} — {project['project_title']}")
    print("Governance only; no mathematical promotion is implied.\n")
    for entry in named["ledger"]["entries"]:
        claim = claims[entry["claim_id"]]
        marker = "*" if entry["claim_id"] == named["claims"].get("active_target") else "-"
        print(f"{marker} {entry['claim_id']}: Gate {entry['gate']}; {entry['epistemic_class']}; [{entry['verification_state']}]; {entry['lifecycle_state']}")
        print(f"  repository status: {claim['status']}")
        print(f"  claim: {claim['claim']}")
    return 0


def changed_paths() -> list[str]:
    try:
        result = subprocess.run(["git", "diff", "--name-only", "HEAD~1", "HEAD"], cwd=ROOT, check=True, capture_output=True, text=True)
    except (OSError, subprocess.CalledProcessError):
        return []
    return [line for line in result.stdout.splitlines() if line]


def run_check(mode: str) -> int:
    if mode == "changed":
        paths = changed_paths()
        if paths:
            print("Changed paths:")
            for path in paths:
                print(f"- {path}")
        else:
            print("Changed paths unavailable or empty.")
        print("CR-0 policy: conservatively running the full governance check.\n")
    errors = validate_all()
    if errors:
        print("Cruthúnas governance check failed:", file=sys.stderr)
        for error in errors:
            print(f"- {error}", file=sys.stderr)
        return 1
    print("Cruthúnas governance check passed.")
    print("Scope: repository coherence only; mathematical claims retain their recorded status.")
    return 0


def main() -> int:
    parser = argparse.ArgumentParser(prog="cruthunas")
    subparsers = parser.add_subparsers(dest="command", required=True)
    check_parser = subparsers.add_parser("check")
    check_mode = check_parser.add_mutually_exclusive_group(required=True)
    check_mode.add_argument("--all", action="store_true")
    check_mode.add_argument("--changed", action="store_true")
    subparsers.add_parser("status")
    adapters_parser = subparsers.add_parser("adapters")
    adapters_parser.add_argument("action", choices=("sync", "check"))
    args = parser.parse_args()

    if args.command == "check":
        return run_check("all" if args.all else "changed")
    if args.command == "status":
        return show_status()
    if args.command == "adapters":
        project = load_json(PROJECT_PATH)
        if args.action == "sync":
            sync_adapters(project)
            return 0
        errors = adapter_errors(project)
        if errors:
            for error in errors:
                print(error, file=sys.stderr)
            return 1
        print("Cruthúnas adapters are synchronized.")
        return 0
    raise AssertionError("unreachable")


if __name__ == "__main__":
    try:
        raise SystemExit(main())
    except GovernanceError as exc:
        print(f"Cruthúnas error: {exc}", file=sys.stderr)
        raise SystemExit(1)
